### ISSUE TITLE
Download button doesn't do anything. 

### ISSUE THREAD

**Issue by Brickmaster1** [MaldLoader/website#5]
The download button brings you to a thanks page but doesn't download anything.

**Comment by hYdos** [comment]
website has not been finished. There are no working builds, only source code at the moment

**Comment by Brickmaster1** [comment]
Oh

**Comment by Brickmaster1** [comment]
There is a functional dev build tho but it's only a dev build I'm guessing

**Comment by hYdos** [comment]
yea and it only runs inside of an IDE, nothing users could download

**Comment by Brickmaster1** [comment]
I'm very interested in modding so this question isn't exactly related to the mod but why is it that certain things will run only in a certain environment? I already experimented with using you source with intellij IDEA and its pretty neat, I have some basic Java knowledge and was just interested and also wondering how you run mods in a dev environment or ever how to build and where I find artifacts. I guess my questions are more on the side of learning the forge and fabric APIs at this point.

**Comment by hYdos** [comment]
stuff doesnt run everywhere because of conditions which change. Dev enviroments (Especially this one, we hard code some paths to things in my computer only). Its more Gradle Tool stuff then Forge/Fabric API stuff. There are plenty of other reasons for other things too but too much to get into here

**Comment by Brickmaster1** [comment]
I have never correctly understood what gradle is but I have seen it used in all Minecraft mods and tons of Java projects in general. If there was any beginner-ish tutorial you could recommend on gradle that would be really neat.

**Comment by Brickmaster1** [comment]
Also what's groovy and kotlin and scala and all the other things I've seen the modding community use?

**Comment by hYdos** [comment]
You dont learn gradle, you either
1. use someone elses build script
2. suffer

Kotlin, Groovy, and Scala are different languages which compile to JVM Bytecode. Most of them try to extend java functionality but in modern java imo they are useless

**Comment by Brickmaster1** [comment]
Oh yeah, and I had one more question, what is maven and all those other services?

**Comment by Brickmaster1** [comment]
I have also been wondering if you put your based loom plugin on a public repo like maven or gradles public repos? Cause the build script can't seem to find it. I have been reading on gradle.
